name: Deploy to FTP

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.0  # Use the desired Node.js version

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Install dependencies and build Next.js app
        env:
          EDGE_STORE_ACCESS_KEY: ${{ secrets.EDGE_STORE_ACCESS_KEY }}
          EDGE_STORE_SECRET_KEY: ${{ secrets.EDGE_STORE_SECRET_KEY }}
          RESEND_KEY: ${{secrets.RESEND_KEY}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          SESSION_SECRET: ${{secrets.SESSION_SECRET}}
          AUTH_SECRET: ${{secrets.AUTH_SECRET}}
          NEXTAUTH_CLIENT: ${{secrets.NEXTAUTH_CLIENT}}
          NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
        run: |
          npm install  # Install project dependencies
          npm run build  # Build Next.js app

      - name: Test FTP Connection
        run: |
          lftp -c "open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; set ssl:verify-certificate no; ls; bye"

      - name: Check DNS Resolution
        run: nslookup ${{ secrets.FTP_SERVER }}

      - name: Deploy via FTP
        run: |
          lftp -c "open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; set ssl:verify-certificate no; mirror -R -e -x .git/ -x .github/ -x .next/ -x node_modules/ ./public ./public_html/school; bye"

